In [4]:
import pandas as pd

df = pd.read_excel('cleaned_hotels.xlsx')

# Print column names
print("Available columns in dataset:", df.columns)

Available columns in dataset: Index(['ID', 'City', 'Location ', 'PType', 'PPN', 'Nights', 'Beds', 'Baths',
       'Reviews', 'Recent'],
      dtype='object')

In [7]:
df = df.rename(columns=lambda x: x.strip())  # Remove extra spaces
df = df.rename(columns={'room type': 'Room_Type'})  # Adjust incorrect column name
df

,ID,City,Location,PType,PPN,Nights,Beds,Baths,Reviews,Recent
0,IND137,Mumbai,NaN,Entire Home/Apartment,NaN,2.0,1.0,1.0,4.0,2022-03-12
1,IND138,Bangalor,Indiranagar,Private Room,1800.0,NaN,1.0,1.0,2.0,15-Feb-23
2,IND139,Delhi,Hauz Khas,Entire Home/Apartment,NaN,3.0,2.0,2.0,NaN,2021/12/25
3,IND140,Chennai,Teynampet,Shared Room,NaN,1.0,NaN,1.0,1.0,"May 5, 2022"
4,IND141,Hyderabad,Jubilee Hills,Entire Home/Apartment,3800.0,3.0,3.0,3.0,5.0,2022-08-20 14:00
5,IND142,Pune,NaN,Private Room,NaN,1.0,1.0,NaN,3.0,10/01/2023
6,IND143,Kolkata,Park Street,Entire Home/Apartment,NaN,2.0,2.0,2.0,4.0,2022-04-15
7,IND144,Mumbai,Colaba,Shared Room,NaN,1.0,1.0,1.0,NaN,"Jun 18, 2022"
8,IND145,Bangalore,Koramangala,Entire Home/Apartment,NaN,3.0,3.0,3.0,6.0,2022-02-28
9,IND146,Chennai,Anna Nagar,Private Room,NaN,1.0,1.0,1.0,2.0,2022-07-10
10,IND147,Hydrabad,Gachibowli,Entire Home/Apartment,NaN,3.0,NaN,3.0,4.0,2022-01-10
11,IND148,Mumbai,Andheri,Private Room,NaN,1.0,1.0,1.0,3.0,"Dec 25, 2021"
12,IND149,Delhi,Dwarka,Shared Room,NaN,1.0,1.0,NaN,2.0,20-Feb-22
13,IND150,Chennai,Egmore,Entire Home/Apartment,NaN,3.0,3.0,3.0,NaN,11/08/2022
14,IND151,Pune,Shivaji Nagar,Private Room,NaN,1.0,1.0,1.0,4.0,2022-05-15
15,IND152,Kolkata,Camac Street,Entire Home/Apartment,NaN,2.0,2.0,2.0,5.0,18-Jun-22
16,IND153,Bangalore,Electronic City,Shared Room,NaN,1.0,NaN,1.0,1.0,2022-09-01
17,IND154,Mumbai,Nariman Point,Entire Home/Apartment,NaN,3.0,3.0,3.0,6.0,2022-03-25 10:00
18,IND155,Hyderabad,Secunderabad,Private Room,NaN,1.0,1.0,1.0,3.0,"July 4, 2022"
19,IND156,Chennai,Thiruvanmiyur,Entire Home/Apartment,NaN,3.0,NaN,3.0,5.0,2022-02-14
20,IND157,Mumbai,Worli,Entire Home/Apartment,NaN,3.0,3.0,NaN,5.0,2022-06-18
21,IND158,Delhi,Aerocity,Private Room,NaN,1.0,1.0,1.0,4.0,"January 2, 2023"
22,IND159,Bangalore,HSR Layout,Shared Room,NaN,1.0,NaN,1.0,2.0,23-Mar-22
23,IND160,Hyderabad,Kondapur,Entire Home/Apartment,NaN,3.0,3.0,3.0,6.0,2022-09-15 18:00
24,IND161,Chennai,Velachery,Private Room,NaN,1.0,1.0,1.0,1.0,10/04/2022
25,IND162,Pune,Koregaon Park,Entire Home/Apartment,NaN,3.0,3.0,3.0,NaN,2022-07-22
26,IND163,Kolkata,Salt Lake,Shared Room,NaN,1.0,1.0,NaN,2.0,2022-05-01
27,IND164,Mumbai,BKC,Entire Home/Apartment,NaN,3.0,4.0,4.0,7.0,2022-04-10
28,IND165,Delhi,Saket,Private Room,NaN,1.0,1.0,1.0,5.0,"August 15, 2022"
29,IND166,Bangalore,MG Road,Entire Home/Apartment,NaN,3.0,4.0,4.0,NaN,2022-03-28
30,IND167,Chennai,Guindy,Entire Home/Apartment,NaN,3.0,3.0,NaN,5.0,2022-08-12
31,IND168,Pune,Hadapsar,Private Room,NaN,1.0,1.0,1.0,3.0,"February 20, 2023"
32,IND169,Kolkata,New Town,Shared Room,NaN,1.0,NaN,1.0,2.0,15-Apr-22
33,IND170,Mumbai,Powai,Entire Home/Apartment,NaN,3.0,3.0,3.0,6.0,2022-09-20 12:00
34,IND171,Delhi,Rohini,Private Room,NaN,1.0,1.0,1.0,4.0,2022-06-01
35,IND172,Bangalore,Jay Nagar,Entire Home/Apartment,NaN,3.0,4.0,4.0,NaN,2022-04-25
36,IND173,Hyderabad,Manikonda,Shared Room,NaN,1.0,1.0,NaN,3.0,2022-07-15
37,IND174,Chennai,Tambaram,Entire Home/Apartment,NaN,3.0,3.0,3.0,5.0,2022-03-18
38,IND175,Pune,Wagholi,Private Room,NaN,1.0,1.0,1.0,4.0,"January 10, 2023"
39,IND176,Kolkata,Baranagar,Entire Home/Apartment,NaN,3.0,3.0,3.0,NaN,2022-08-05
40,IND177,Mumbai,Ghatkopar,Shared Room,NaN,1.0,NaN,1.0,2.0,22-May-22
41,IND178,Delhi,Dilshad Garden,Entire Home/Apartment,NaN,3.0,4.0,4.0,7.0,2022-05-12
42,IND179,Bangalore,Electronic City Phase 2,Private Room,NaN,1.0,1.0,1.0,5.0,"August 25, 2022"
43,IND180,Hyderabad,Kukatpally,Entire Home/Apartment,NaN,3.0,4.0,4.0,NaN,2022-06-28
44,IND181,Chennai,Adyar,Shared Room,NaN,1.0,1.0,NaN,2.0,2022-04-01
45,IND182,Pune,Bavdhan,Entire Home/Apartment,NaN,3.0,3.0,3.0,6.0,2022-09-10 18:00
46,IND183,Kolkata,Lake Town,Private Room,NaN,1.0,1.0,1.0,3.0,"February 15, 2023"
47,IND184,Mumbai,Santacruz,Entire Home/Apartment,NaN,3.0,4.0,4.0,7.0,2022-07-22
48,IND185,Delhi,Pitampura,Shared Room,NaN,1.0,NaN,1.0,2.0,10/03/2022
49,IND186,Bangalore,Marathahalli,Entire Home/Apartment,NaN,3.0,5.0,5.0,NaN,2022-05-05

In [9]:
import pandas as pd

# Load the cleaned dataset
df = pd.read_excel('cleaned_hotels.xlsx')

# Ensure the 'Reviews' column exists and is numeric
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')

# Check if 'PType' and 'Reviews' exist
if 'PType' not in df.columns:
    raise KeyError("Column 'PType' not found in the dataset!")

if 'Reviews' not in df.columns:
    raise KeyError("Column 'Reviews' not found in the dataset!")

# Get the best room (highest Reviews) under each Type (PType) in each City
best_rooms = df.loc[df.groupby(['City', 'PType'])['Reviews'].idxmax().dropna()]

# Save the result to an Excel file
best_rooms.to_excel('best_rooms_per_type_per_city.xlsx', index=False)

# Print the result
print(best_rooms)

        ID       City                Location                   PType     PPN  \
1   IND138   Bangalor              Indiranagar           Private Room  1800.0
8   IND145  Bangalore              Koramangala  Entire Home/Apartment     NaN
42  IND179  Bangalore  Electronic City Phase 2           Private Room     NaN
22  IND159  Bangalore               HSR Layout            Shared Room     NaN
19  IND156    Chennai            Thiruvanmiyur  Entire Home/Apartment     NaN
9   IND146    Chennai               Anna Nagar           Private Room     NaN
44  IND181    Chennai                    Adyar            Shared Room     NaN
41  IND178      Delhi           Dilshad Garden  Entire Home/Apartment     NaN
28  IND165      Delhi                    Saket           Private Room     NaN
48  IND185      Delhi                Pitampura            Shared Room     NaN
12  IND149     Delhi                    Dwarka            Shared Room     NaN
23  IND160  Hyderabad                 Kondapur  Entire Home/Apartment     NaN
18  IND155  Hyderabad             Secunderabad           Private Room     NaN
36  IND173  Hyderabad                Manikonda            Shared Room     NaN
10  IND147   Hydrabad               Gachibowli  Entire Home/Apartment     NaN
15  IND152    Kolkata             Camac Street  Entire Home/Apartment     NaN
46  IND183    Kolkata                Lake Town           Private Room     NaN
26  IND163    Kolkata                Salt Lake            Shared Room     NaN
27  IND164     Mumbai                      BKC  Entire Home/Apartment     NaN
11  IND148     Mumbai                 Andheri            Private Room     NaN
40  IND177     Mumbai                Ghatkopar            Shared Room     NaN
45  IND182       Pune                  Bavdhan  Entire Home/Apartment     NaN
14  IND151       Pune            Shivaji Nagar           Private Room     NaN

    Nights  Beds  Baths  Reviews             Recent
1      NaN   1.0    1.0      2.0          15-Feb-23
8      3.0   3.0    3.0      6.0         2022-02-28
42     1.0   1.0    1.0      5.0    August 25, 2022
22     1.0   NaN    1.0      2.0          23-Mar-22
19     3.0   NaN    3.0      5.0         2022-02-14
9      1.0   1.0    1.0      2.0         2022-07-10
44     1.0   1.0    NaN      2.0         2022-04-01
41     3.0   4.0    4.0      7.0         2022-05-12
28     1.0   1.0    1.0      5.0    August 15, 2022
48     1.0   NaN    1.0      2.0         10/03/2022
12     1.0   1.0    NaN      2.0          20-Feb-22
23     3.0   3.0    3.0      6.0   2022-09-15 18:00
18     1.0   1.0    1.0      3.0       July 4, 2022
36     1.0   1.0    NaN      3.0         2022-07-15
10     3.0   NaN    3.0      4.0         2022-01-10
15     2.0   2.0    2.0      5.0          18-Jun-22
46     1.0   1.0    1.0      3.0  February 15, 2023
26     1.0   1.0    NaN      2.0         2022-05-01
27     3.0   4.0    4.0      7.0         2022-04-10
11     1.0   1.0    1.0      3.0       Dec 25, 2021
40     1.0   NaN    1.0      2.0          22-May-22
45     3.0   3.0    3.0      6.0   2022-09-10 18:00
14     1.0   1.0    1.0      4.0         2022-05-15